#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable opendmarc.service

  if test -f "disabled.bin"; then
    echo "dmarc is already disabled."
  else
    touch "disabled.bin"
    if systemctl is-active --quiet opendmarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop opendmarc.service
    else
      echo "dmarc will be disabled on next reboot."
    fi
  fi

fi


