#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable opendmarc-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl --quiet enable opendmarc.service

  if test -f "enabled"; then
    echo "dmarc is already enabled."
  elif test -f "disabled"; then
    mv "disabled" "enabled"
    /usr/bin/sudo /usr/bin/systemctl restart opendmarc-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl restart opendmarc.service
  else
    touch "enabled"
    echo "arc will be enabled on next reboot."
  fi

fi

