#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable opendmarc.service

  if test ! -f "disabled.bin"; then
    echo "dmarc is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet opendmarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart opendmarc-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart opendmarc.service
    else
      echo "dmarc will be enabled on next reboot."
    fi
  fi

fi

